<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Configurations\ConfigurationController;
use App\Http\Controllers\GlobalVariableController as VariableGlobal;
use Illuminate\Http\Request;

class GlobalVariableController extends Controller
{

    public static $voucherType = [
        'Compliment' => 'C',
        'Discount' => 'D',
        'Sale' => 'S',
    ];

    public static $voucherStatus = [
        'Active'=> 'A',
        'Used'=> 'U',
        'Expire'=> 'E',
    ];

    public static $voucherStatusSold = [
        'Sold'=> 'S',
        'Redeemed'=> 'R',
        'Compliment'=> 'C',
    ];

    public static $voucherStatusApprove = [
        'Unapprove'=> 'U',
        'Approved'=> 'A',
        'NotApproved'=> 'N'
    ];

    public static $journalType = [
        'CashIn' => '1',
        'CashOut' => '2',
        'CashTransfer' => '3',
        'BankIn' => '4',
        'BankOut' => '5',
        'BankTransfer' => '6',
        'CreditCardReconciliation' => '7',
        'Cheque' => '8',
        'Other' => '9'
    ];

    public static $departmentType = [
        'Income' => 'I',
        'NonIncome' => 'N',
        'Other' => 'O',
    ];

    public static $journalGroup = [
        'CapitalReceipt' => 'CAPT',
        'Receiving' => 'RECV',
        'ARPayment' => 'PYAR',
        'Loan' => 'LOAN',
        'Investment' => 'INVS',
        'BankWithdrawal' => 'BKWD',
        'AssetPurchasing' => 'PCAS',
        'InventoryPurchasing' => 'PCIV',
        'OtherPurchasing' => 'PCOT',
        'APPayment' => 'PYAP',
        'Expense' => 'EXPE',
        'BankDeposit' => 'BKDP',
        'CashTransfer' => 'TRCS',
        'BankTransfer' => 'TRBK',
        'AccountPayable' => 'ACPY',
        'AccountReceivable' => 'ACRV',
        'Costing' => 'COST',
        'FixedAsset' => 'FAST'
    ];

    public static $mode = [
        'Update' => 'U',
        'Delete' => 'D',
        'Insert' => 'I',
    ];

    public static $allowMultiLoginUser = false;

    public static $cryptoKey = 'cakrat3ndadOs';

    public static $accessSpecialOrder = [
        'UnlockReservation' => 0,
        'VoidReservation' => 1,
        'VoidDeposit' => 2,
        'CorrectDeposit' => 3,
        'DecreaseStay' => 4,
        'ScheduledRate' => 5,
        'Breakdown' => 6,
        'ExtraCharge' => 7,
        'ComplimentGuest' => 8,
        'HouseUseGuest' => 9,
        'MoveRoom' => 10,
        'VoidSubFolio' => 11,
        'CorrectSubFolio' => 12,
        'CancelCheckIn' => 13,
        'CancelCheckOut' => 14,
        'CreateMasterFolio' => 15,
        'PrintMoreInvoice' => 16,
        'ModifyClosedJournal' => 17,
        'TransferToDeskFolio' => 18,
        'TransferToMasterFolio' => 19,
        'BusinessSource' => 20,
        'OverrideRateDiscount' => 21
    ];

    public static $journalPrefix = [
        'AccountPayable' => 'AP',
        'AccountReceivable' => 'AR',
        'Adjustment' => 'JA',
        'BeginningYear' => 'JB',
        'Disbursement' => 'JD',
        'FixedAsset' => 'JF',
        'Inventory' => 'JI',
        'Manual' => 'JM',
        'Receive' => 'JR',
        'Transaction' => 'JT',
    ];

    public static $userAccessType = [
        'Special' => 'access_special'
    ];

    public static $constProgramVariable = [
        'DefaultSystemCode' => 'H',
        'DatabaseVersion' => '07.03.06.00',
        'SettingFileName' => 'Setting.ini',
        'WallpaperListFile' => 'WallpaperH.txt',
        'TempImageFile' => 'TempImage.jpg',
        'InvoiceNumberPrefix' => 'INV',
        'APNumberPrefix' => 'AP',
        'ARNumberPrefix' => 'AR',
        'StockTransferNumberPrefix' => 'ST',
        'CostingNumberPrefix' => 'CO',
        'OTPPrefix' => 'OTP',
        'CompanyCodePrefix' => 'C',
        'CityOtherCode' => 'OTH',
        'AddKey' => 8,
        'MinPasswordLength' => 6,
        'MaxLoginTry' => 3,
        'MaxOTPGenerate' => 50,
        'ConfigurationAccess' => 37];

    public static $formType = [
        'GuestInHouse' => 'I',
        'FolioHistory' => 'H',
        'Reservation' => 'R'
    ];

    public static $reservationStatus = [
        'New' => 'N',
        'WaitList' => 'W',
        'InHouse' => 'I',
        'Canceled' => 'C',
        'NoShow' => 'S',
        'Void' => 'V',
        'CheckOut' => 'O'];

    public static $reservationStatus2 = [
        'Tentative' => 'T',
        'Confirm' => 'C',
        'Guaranteed' => 'G'];

    public static $reportList = [
        'AllReservation' => 1001,
        'Arrival' => 1002,
        'Departure' => 1003,
        'ExpectedArrival' => 1004,
        'Cancel' => 1005,
        'NoShow' => 1006,
        'Void' => 1007,
        'GuestForecast' => 1008,
        'Availability' => 1009,
        'CurrentInHouse' => 2001,
        'GuestInHouse' => 2002,
        'GuestList' => 2003,
        'ExpectedDeparture' => 2004,
        'DepartureList' => 2005,
        'CashierReport' => 2006,
        'DailyFlashReport' => 2007,
        'RoomStatus' => 3001,
        'Unavailable' => 3002,
        'User' => 4001,

        'RegistrationFormReservation' => 90001,
        'RegistrationFormInHouse' => 90002,
        'Receipt' => 91000,
        'ReceiptDeposit' => 91001,
        'ReceiptFolio' => 91002,
        'ProformaInvoice' => 92001,
        'ProformaInvoiceDetail' => 92002,
        'ConfirmationLetter' => 92003,
        'Folio' => 93001,

        'RoomCheckList' => 94001,

        'CityLedgerInvoice' => 95001,
        'InvoicePaymentReceipt' => 95002,

    ];

    public static $folioStatus = [
        'Open' => 'O',
        'Closed' => 'C',
        'CancelCheckIn' => 'I'];

    public static $transactionType = [
        'Debit' => 'D',
        'Credit' => 'C'];

    public static $roomStatus = [
        'Ready' => 'R',
        'Dirty' => 'D',
        'Clean' => 'C',
        'Vacant'=>'V',
        'Occupied'=>'O',
        'HouseUse'=>'H',
        'Compliment'=>'P',
        'DontDisturb'=>'DD',
        'DoubleLock'=>'DL',
        'SleepOut'=>'SO',
        'PleaseClean'=>'PC',
        'OutOfOrder'=>'OO',
        'OfficeUse'=>'OF',
        'UnderConstruction' => 'UC'
    ];

    public static $contactPersonType =[
        'Guest' => 'G',
        'Company' => 'C',
        'Invoice' => 'I',
        'RoomOwner' => 'R'
    ];

    public static $foreignCashTableID = [
        'GuestDeposit'=> 1,
        'SubFolio' => 2,
        'InvoicePayment' => 31
    ];

    public static $system =[
        'CakrasoftAssetManagementSystem' => 'A',
        'CakrasoftBanquetManagementSystem' => 'B',
        'CakrasoftAccountingSystem' => 'C',
        'CakrasoftHotelSystem' => 'H',
        'CakrasoftHouseKeepingMobileSystem' => 'K',
        'CakrasoftCorporateSystem' => 'O',
        'CakrasoftPointofSales' => 'P',
        'CakrasoftCaptainOrderMobileSystem' => 'S'
    ];

    public static $folioType = [
        'GuestFolio' => 'F',
        'MasterFolio' => 'M',
        'DeskFolio' => 'D'
    ];

    public static $subFolioGroup = [
        'A' => 'A',
        'B' => 'B',
        'C' => 'C',
        'D' => 'D'
    ];

    public static $bankAccountType = [
        'CashAccount' => 'C',
        'SavingAccount' => 'S',
        'CreditAccount' => 'R',
        'ChequeAccount' => 'Q'
    ];

    public static $folioTransferBy = [
        'NoTransfer' => 'N',
        'ByAccount' => 'A',
        'ByAccountSubGroup' => 'S'
    ];

    public static $postingType = [
        'None' => 'N',
        'Deposit' => 'D',
        'Transfer' => 'T',
        'Room' => 'R',
        'ExtraCharge' => 'E'
    ];

    public static $accountGroup = [
        'Charge' => '1',
        'Payment' => '2',
        'TaxAndService' => '3',
        'Transfer' => '4',
    ];

    public static $accountSubGroup = [
        'RoomCharge' => 'ROOM',
        'AccountPayable' => 'ACPY',
        'Payment'=> 'PYMT',
        'CreditDebitCard' => 'CRDB',
        'BankTransfer' => 'BKTR',
        'AccountReceivable' => 'ACRV',
        'Compliment' => 'CMPL'
    ];

    public static $inventoryItemGroup = [
        'Food' => 'FOOD',
        'Beverage' => 'BVRG'
    ];

        public static $chargeFrequency = [
        'OnceOnly' => '0',
        'Daily'=> '1',
        'Weekly' => '2',
        'Monthly' => '3'
    ];

    public static $commissionType = [
        'PercentFirstNightFullRate' => '1',
        'PercentPerNightFullRate' => '2',
        'PercentFirstNightNettRate' => '3',
        'PercentPerNightNettRate' => '4',
        'FixAmountFirstNight' => '5',
        'FixAmountPerNight' => '6'
    ];

    public static $budgetType = [
        'Manual' => 'M',
        'Average' => 'A',
        'Percentage' => 'P',
        'Daily' => 'D'
    ];

    public static $configurationCategory = [
    'General' => 'GENERAL',
    'Form' => 'FORM',
    'FormatSetting' => 'FORMAT_SETTING',
    'Grid' => 'GRID',
    'Report' => 'REPORT',
    'WeekendDay' => 'WEEKEND_DAY',
    'ReportSignature' => 'REPORT_SIGNATURE',
    'ReportTemplate' => 'REPORT_TEMPLATE',
    'Other' => 'OTHER',
    'Reservation' => 'RESERVATION',
    'DefaultVariable' => 'DEFAULT_VARIABLE',
    'AmountPreset' => 'AMOUNT_PRESET',
    'CustomField' => 'CUSTOM_FIELD',
    'CustomLookupField' => 'CUSTOM_LOOKUP_FIELD',
    'MemberVoucherGift' => 'MEMBER_VOUCHER_GIFT',
    'Accounting' => 'ACCOUNTING',
    'GlobalAccount' => 'GLOBAL_ACCOUNT',
    'GlobalJournalAccount' => 'GLOBAL_GL_ACCOUNT',
    'PaymentAccount' => 'PAYMENT_ACCOUNT',
    'SubDepartment' => 'SUB_DEPARTMENT',
    'GlobalDepartment' => 'GLOBAL_DEPARTMENT',
    'GlobalSubDepartment' => 'GLOBAL_SUB_DEPT',
    'GlobalOther' => 'GLOBAL_OTHER',
    'Personal' => 'PERSONAL',
    'Invoice' => 'INVOICE',
    'Folio' => 'FOLIO',
    'OtherForm' => 'OTHER_FORM',
    'CompanyBankAccount' => 'COMPANY_BANK_ACCOUNT',
    'FloorPlan' => 'FLOOR_PLAN',
    'RoomStatusColor' => 'ROOM_STATUS_COLOR',
    'Keylock' => 'KEYLOCK',
    'PABX' => 'PABX',
    'RoomCosting' => 'ROOM_COSTING',
    'OtherHK' => 'OTHER_HK',
    'ServiceIPTV' => 'SERVICE_IPTV',
    'ServiceCCMS' => 'SERVICE_CCMS',
    'Mikrotik' => 'MIKROTIK',
    'Notification' => 'NOTIFICATION',
    'Inventory' => 'INVENTORY'
];

public static $configurationName = [
//General
    'DatabaseVersion' => 'DATABASE_VERSION',
    'IsReplication' => 'IS_REPLICATION',
    'UseChildRate' => 'USE_RATE_CHILD',
    'IsRoomByName' => 'IS_ROOM_BY_NAME',
    'LogOffTriggerAddress' => 'LOG_OFF_TRIGGER_ADDRESS',
//Form
    'FormMDIChild' => 'FORM_MDI_CHILD',
    'RequiredFieldColor' => 'REQUIRED_FIELD_COLOR',
//Format Setting
    'ShortDateFormat' => 'SHORT_DATE_FORMAT',
    'DateSeparator' => 'DATE_SEPARATOR',
    'CurrencyFormat' => 'CURRENCY_FORMAT',
    'DecimalSeparator' => 'DECIMAL_SEPARATOR',
    'ThousandsSeparator' => 'THOUSANDS_SEPARATOR',
    'Timezone' => 'TIMEZONE',
//Grid
    'ShowGridGroupByBox' => 'SHOW_GRID_GROUP_BY_BOX',
    'GridCanEditCell' => 'GRID_CAN_EDIT_CELL',
    'LimitGrid' => 'LIMIT_GRID',
    'GridRowHeight' => 'GRID_ROW_HEIGHT',
    'DueDateColor' => 'DUE_DATE_COLOR',
//Report
    'LogoWidth' => 'LOGO_WIDTH',
    'ReportHeaderAligment' => 'REPORT_HEADER_ALIGNMENT',
//Weekend Day
    'FridayAsWeekend' => 'FRIDAY_AS_WEEKEND',
    'SaturdayAsWeekend' => 'SATURDAY_AS_WEEKEND',
    'SundayAsWeekend' => 'SUNDAY_AS_WEEKEND',
//Report Signature
    'ShowPreparedBy' => 'SHOW_PREPARED_BY',
    'PreparedBy' => 'PREPARED_BY',
    'ShowCheckedBy' => 'SHOW_CHECKED_BY',
    'CheckedBy' => 'CHECKED_BY',
    'ShowApprovedBy' => 'SHOW_APPROVED_BY',
    'ApprovedBy' => 'APPROVED_BY',
    'ShowInDailyRevenueReport' => 'SHOW_IN_DAILY_REVENUE_REPORT',
    'ShowInRoomStatisticReport' => 'SHOW_IN_ROOM_STATISTIC_REPORT',
//Report Template
    'CashierReport' => 'CASHIER_REPORT',
    'CashRemittance' => 'CASH_REMITTANCE',
    'BreakfastList' => 'BREAKFAST_LIST',
    'PickUpService' => 'PICK_UP_SERVICE',
    'DropService' => 'DROP_SERVICE',
    'HKChecklist' => 'HK_CHECK_LIST',
    'HKRoomStatus' => 'HK_ROOM_STATUS',
    'HKRoomStatusSummary' => 'HK_ROOM_STATUS_SUMMARY',
    'HKRoomDiscrepancy' => 'HK_ROOM_DISCREPANCY',
    'HKRoomAttendantControlSheet' => 'HK_ROOM_ATTENDANT_CONTROL_SHEET',
    'DailyRevenueReport' => 'DAILY_REVENUE_REPORT',
    'DailyRevenueReportSummary' => 'DAILY_REVENUE_REPORT_SUMMARY',
    'GuestInHouseListing' => 'GUEST_IN_HOUSE_LISTING',
    'RoomStatistic' => 'ROOM_STATISTIC',
    'RoomProduction' => 'ROOM_PRODUCTION',
    'GuestForecast' => 'GUEST_FORECAST',
//Other
    'ShowTransferOnCashierReport' => 'SHOW_TRANSFER_ON_CASHIER_REPORT',
    'IncomeBudgetCalculateEachDay' => 'INCOME_BUDGET_CALCULATE_EACH_DAY',
    'InsertServerIDOnPrefixNumber' => 'INSERT_SERVER_ID_ON_PREFIX_NUMBER',
    'CalculateAllRoomRevenueSubGroup' => 'CALCULATE_ALL_ROOM_REVENUE',
    'CompanyTypeTravelAgent' => 'COMPANY_TYPE_TRAVEL_AGENT',
//Reservation
    'PostFirstNightCharge' => 'POST_FIRST_NIGHT_CHARGE',
    'PostDiscount' => 'POST_DISCOUNT',
    'KeylockLimit' => 'KEYLOCK_LIMIT',
    'CheckOutLimit' => 'CHECK_OUT_LIMIT',
    'IsRoomNumberRequired' => 'IS_ROOM_NUMBER_REQUIRED',
    'IsBusinessSourceRequired' => 'IS_BUSINESS_SOURCE_REQUIRED',
    'IsMarketRequired' => 'IS_MARKET_REQUIRED',
    'IsTitleRequired' => 'IS_TITLE_REQUIRED',
    'IsNationalityRequired' => 'IS_NATIONALITY_REQUIRED',
    'IsPhone1Required' => 'IS_PHONE1_REQUIRED',
    'IsEmailRequired' => 'IS_EMAIL_REQUIRED',
    'IsCompanyRequired' => 'IS_COMPANY_REQUIRED',
    'IsHKNoteRequired' => 'IS_HK_NOTE_REQUIRED',
    'IsTAVoucherRequired' => 'IS_TA_VOUCHER_REQUIRED',
    'IsStateRequired' => 'IS_STATE_REQUIRED',
    'IsCityRequired' => 'IS_CITY_REQUIRED',
    'FilterRateByMarket' => 'FILTER_RATE_BY_MARKET',
    'FilterRateByCompany' => 'FILTER_RATE_BY_COMPANY',
    'AlwaysShowPublishRate' => 'ALWAYS_SHOW_PUBLISH_RATE',
    'LockFolioOnCheckIn' => 'LOCK_FOLIO_ON_CHECK_IN',
    'AutoGenerateCompanyCode' => 'AUTO_GENERATE_COMPANY_CODE',
    'CompanyCodeDigit' => 'COMPANY_CODE_DIGIT',
//Default Variable
    'DVRoomType' => 'DV_ROOM_TYPE',
    'DVRoomRate' => 'DV_ROOM_RATE',
    'DVSubDepartment' => 'DV_SUB_DEPARTMENT',
    'DVPaymentType' => 'DV_PAYMENT_TYPE',
    'DVComplimentRate' => 'DV_COMPLIMENT_RATE',
    'DVHouseUseRate' => 'DV_HOUSE_USE_RATE',
    'DVMarket' => 'DV_MARKET',
    'DVIndividualMarket' => 'DV_INDIVIDUAL_MARKET',
//Amount Preset
    'APPreset1' => 'PRESET1',
    'APPreset2' => 'PRESET2',
    'APPreset3' => 'PRESET3',
    'APPreset4' => 'PRESET4',
    'APPreset5' => 'PRESET5',
    'APPreset6' => 'PRESET6',
    'APPreset7' => 'PRESET7',
    'APPreset8' => 'PRESET8',
//Custom Field
    'CustomFieldName01' => 'CUSTOM_FIELD_NAME01',
    'CustomFieldName02' => 'CUSTOM_FIELD_NAME02',
    'CustomFieldName03' => 'CUSTOM_FIELD_NAME03',
    'CustomFieldName04' => 'CUSTOM_FIELD_NAME04',
    'CustomFieldName05' => 'CUSTOM_FIELD_NAME05',
    'CustomFieldName06' => 'CUSTOM_FIELD_NAME06',
    'CustomFieldName07' => 'CUSTOM_FIELD_NAME07',
    'CustomFieldName08' => 'CUSTOM_FIELD_NAME08',
    'CustomFieldName09' => 'CUSTOM_FIELD_NAME09',
    'CustomFieldName10' => 'CUSTOM_FIELD_NAME10',
    'CustomFieldName11' => 'CUSTOM_FIELD_NAME11',
    'CustomFieldName12' => 'CUSTOM_FIELD_NAME12',
    'CustomFieldDefaultValue01' => 'CUSTOM_FIELD_DEFAULT_VALUE01',
    'CustomFieldDefaultValue02' => 'CUSTOM_FIELD_DEFAULT_VALUE02',
    'CustomFieldDefaultValue03' => 'CUSTOM_FIELD_DEFAULT_VALUE03',
    'CustomFieldDefaultValue04' => 'CUSTOM_FIELD_DEFAULT_VALUE04',
    'CustomFieldDefaultValue05' => 'CUSTOM_FIELD_DEFAULT_VALUE05',
    'CustomFieldDefaultValue06' => 'CUSTOM_FIELD_DEFAULT_VALUE06',
    'CustomFieldDefaultValue07' => 'CUSTOM_FIELD_DEFAULT_VALUE07',
    'CustomFieldDefaultValue08' => 'CUSTOM_FIELD_DEFAULT_VALUE08',
    'CustomFieldDefaultValue09' => 'CUSTOM_FIELD_DEFAULT_VALUE09',
    'CustomFieldDefaultValue10' => 'CUSTOM_FIELD_DEFAULT_VALUE10',
    'CustomFieldDefaultValue11' => 'CUSTOM_FIELD_DEFAULT_VALUE11',
    'CustomFieldDefaultValue12' => 'CUSTOM_FIELD_DEFAULT_VALUE12',
//Custom Lookup Field
    'CustomLookupFieldName01' => 'CUSTOM_LOOKUP_FIELD_NAME01',
    'CustomLookupFieldName02' => 'CUSTOM_LOOKUP_FIELD_NAME02',
    'CustomLookupFieldName03' => 'CUSTOM_LOOKUP_FIELD_NAME03',
    'CustomLookupFieldName04' => 'CUSTOM_LOOKUP_FIELD_NAME04',
    'CustomLookupFieldName05' => 'CUSTOM_LOOKUP_FIELD_NAME05',
    'CustomLookupFieldName06' => 'CUSTOM_LOOKUP_FIELD_NAME06',
    'CustomLookupFieldName07' => 'CUSTOM_LOOKUP_FIELD_NAME07',
    'CustomLookupFieldName08' => 'CUSTOM_LOOKUP_FIELD_NAME08',
    'CustomLookupFieldName09' => 'CUSTOM_LOOKUP_FIELD_NAME09',
    'CustomLookupFieldName10' => 'CUSTOM_LOOKUP_FIELD_NAME10',
    'CustomLookupFieldName11' => 'CUSTOM_LOOKUP_FIELD_NAME11',
    'CustomLookupFieldName12' => 'CUSTOM_LOOKUP_FIELD_NAME12',
    'CustomLookupFieldDefaultValue01' => 'CUSTOM_LOOKUP_FIELD_DEFAULT_VALUE01',
    'CustomLookupFieldDefaultValue02' => 'CUSTOM_LOOKUP_FIELD_DEFAULT_VALUE02',
    'CustomLookupFieldDefaultValue03' => 'CUSTOM_LOOKUP_FIELD_DEFAULT_VALUE03',
    'CustomLookupFieldDefaultValue04' => 'CUSTOM_LOOKUP_FIELD_DEFAULT_VALUE04',
    'CustomLookupFieldDefaultValue05' => 'CUSTOM_LOOKUP_FIELD_DEFAULT_VALUE05',
    'CustomLookupFieldDefaultValue06' => 'CUSTOM_LOOKUP_FIELD_DEFAULT_VALUE06',
    'CustomLookupFieldDefaultValue07' => 'CUSTOM_LOOKUP_FIELD_DEFAULT_VALUE07',
    'CustomLookupFieldDefaultValue08' => 'CUSTOM_LOOKUP_FIELD_DEFAULT_VALUE08',
    'CustomLookupFieldDefaultValue09' => 'CUSTOM_LOOKUP_FIELD_DEFAULT_VALUE09',
    'CustomLookupFieldDefaultValue10' => 'CUSTOM_LOOKUP_FIELD_DEFAULT_VALUE10',
    'CustomLookupFieldDefaultValue11' => 'CUSTOM_LOOKUP_FIELD_DEFAULT_VALUE11',
    'CustomLookupFieldDefaultValue12' => 'CUSTOM_LOOKUP_FIELD_DEFAULT_VALUE12',
//Member Voucher and Gift
    'MemberPointExpire' => 'MEMBER_POINT_EXPIRE',
    'MemberAutoUpdateMemberProfile' => 'MEMBER_AUTO_UPDATE_MEMBER_PROFILE',
    'VoucherLength' => 'VOUCHER_LENGTH',
    'VoucherExpire' => 'VOUCHER_EXPIRE',
    'VoucherPointRedeem' => 'VOUCHER_POINT_REDEEM',
    'VoucherDefaultPrice' => 'VOUCHER_DEFAULT_PRICE',
    'VoucherDescription' => 'VOUCHER_DESCRIPTION',
    'VoucherTemplate' => 'VOUCHER_TEMPLATE',
//Accounting
    'IsAccrualBase' => 'IS_ACCRUAL_BASE',
    'SubDepartmentAllCCAdmin' => 'SUB_DEPARTMENT_ALL_CC_ADMIN',
//Global Account
    'AccountRoomCharge' => 'ACCOUNT_ROOM_CHARGE',
    'AccountExtraBed' => 'ACCOUNT_EXTRA_BED',
    'AccountCanceletionFee' => 'ACCOUNT_CANCELETION_FEE',
    'AccountNoShow' => 'ACCOUNT_NO_SHOW',
    'AccountBreakfast' => 'ACCOUNT_BREAKFAST',
    'AccountTelephone' => 'ACCOUNT_TELEPHONE',
    'AccountAPRefundDeposit' => 'ACCOUNT_AP_REFUND_DEPOSIT',
    'AccountAPCommission' => 'ACCOUNT_AP_COMMISSION',
    'AccountCreditCardAdm' => 'ACCOUNT_CC_ADM',
    'AccountCash' => 'ACCOUNT_CASH',
    'AccountCityLedger' => 'ACCOUNT_CITY_LEDGER',
    'AccountVoucher' => 'ACCOUNT_VOUCHER',
    'AccountVoucherCompliment' => 'ACCOUNT_VOUCHER_COMPLIMENT',
    'AccountTax' => 'ACCOUNT_TAX',
    'AccountService' => 'ACCOUNT_SERVICE',
    'AccountTransferDepositReservation' => 'ACCOUNT_TRANSFER_DEPOSIT_RESERVATION',
    'AccountTransferDepositReservationToFolio' => 'ACCOUNT_TRANSFER_DEPOSIT_RESERVATION_TO_FOLIO',
    'AccountTransferCharge' => 'ACCOUNT_TRANSFER_CHARGE',
    'AccountTransferPayment' => 'ACCOUNT_TRANSFER_PAYMENT',
//Global Journal Account
    'JAGuestLedger' => 'GUEST_LEDGER',
    'JAAPVoucher' => 'AP_VOUCHER',
    'JAGuestDeposit' => 'GUEST_DEPOSIT',
    'JAGuestDepositReservation' => 'GUEST_DEPOSIT_RESERVATION',
    'JAPLBeginningYear' => 'PL_BEGINNING_YEAR',
    'JAPLCurrentYear' => 'PL_CURRENT_YEAR',
    'JAPLCurrency' => 'PL_CURRENCY',
    'JAIncomeVoucherExpire' => 'INCOME_VOUCHER_EXPIRE',
    'JAInvoiceDiscount' => 'INVOICE_DISCOUNT',
    'JACreditCardAdm' => 'CREDIT_CARD_ADMINISTRATION',
//Payment Account
    'PYAccount01' => 'ACCOUNT01',
    'PYAccount02' => 'ACCOUNT02',
    'PYAccount03' => 'ACCOUNT03',
    'PYAccount04' => 'ACCOUNT04',
    'PYAccount05' => 'ACCOUNT05',
    'PYAccount06' => 'ACCOUNT06',
    'PYAccount07' => 'ACCOUNT07',
    'PYAccount08' => 'ACCOUNT08',
    'PYAccount09' => 'ACCOUNT09',
    'PYAccount10' => 'ACCOUNT10',
    'PYAccount11' => 'ACCOUNT11',
    'PYAccount12' => 'ACCOUNT12',
//Payment Account Name
    'PYNAccount01' => 'ACCOUNT_NAME01',
    'PYNAccount02' => 'ACCOUNT_NAME02',
    'PYNAccount03' => 'ACCOUNT_NAME03',
    'PYNAccount04' => 'ACCOUNT_NAME04',
    'PYNAccount05' => 'ACCOUNT_NAME05',
    'PYNAccount06' => 'ACCOUNT_NAME06',
    'PYNAccount07' => 'ACCOUNT_NAME07',
    'PYNAccount08' => 'ACCOUNT_NAME08',
    'PYNAccount09' => 'ACCOUNT_NAME09',
    'PYNAccount10' => 'ACCOUNT_NAME10',
    'PYNAccount11' => 'ACCOUNT_NAME11',
    'PYNAccount12' => 'ACCOUNT_NAME12',
//Sub Department
    'SD01' => 'SD01',
    'SD02' => 'SD02',
    'SD03' => 'SD03',
    'SD04' => 'SD04',
    'SD05' => 'SD05',
    'SD06' => 'SD06',
    'SD07' => 'SD07',
//Sub Department Name
    'SDN01' => 'SD_NAME01',
    'SDN02' => 'SD_NAME02',
    'SDN03' => 'SD_NAME03',
    'SDN04' => 'SD_NAME04',
    'SDN05' => 'SD_NAME05',
    'SDN06' => 'SD_NAME06',
    'SDN07' => 'SD_NAME07',
//Global Department
    'DFoodBeverage' => 'DEPARTMENT_FOOD_BEVERAGE',
//Global Sub Department
    'SDFrontOffice' => 'SUB_DEPARTMENT_FRONT_OFFICE',
    'SDHouseKeeping' => 'SUB_DEPARTMENT_HOUSE_KEEPING',
    'SDBanquet' => 'SUB_DEPARTMENT_BANQUET',
    'SDAccounting' => 'SUB_DEPARTMENT_ACCOUNTING',
//Global Other
    'GOPaymentType' => 'PAYMENT_TYPE',
//Personal
    'DRName' => 'DR_NAME',
    'DRPosition' => 'DR_POSITION',
    'HMName' => 'HM_NAME',
    'HMPosition' => 'HM_POSITION',
    'FHName' => 'FH_NAME',
    'FHPosition' => 'FH_POSITION',
    'IAName' => 'IA_NAME',
    'IAPosition' => 'IA_POSITION',
    'GCName' => 'GC_NAME',
    'GCPosition' => 'GC_POSITION',
//Invoice
    'InvoiceRemark' => 'INVOICE_REMARK',
    'InvoiceNote' => 'INVOICE_NOTE',
    'InvoiceAPNote' => 'INVOICE_AP_NOTE',
    'InvoiceTemplate' => 'INVOICE_TEMPLATE',
//Folio
    'DefaultFolio' => 'DEFAULT_FOLIO',
    'FolioFooter' => 'FOLIO_FOOTER',
    'AllowZeroAmount' => 'ALLOW_ZERO_AMOUNT',
    'PrintRegFormAfterCheckIn' => 'PRINT_REG_FORM_AFTER_CHECK_IN',
    'ShowRate' => 'SHOW_RATE',
//Other Form
    'RegistrationFormReservation' => 'REGISTRATION_FORM_RESERVATION',
    'RegistrationFormInHouse' => 'REGISTRATION_FORM_IN_HOUSE',
    'ConfirmationLetter' => 'CONFIRMATION_LETTER',
    'GuaranteedLetter' => 'GUARANTEE_LETTER',
    'ProformaInvoice' => 'PROFORMA_INVOICE',
    'ProformaInvoiceDetail' => 'PROFORMA_INVOICE_DETAIL',
    'TaxServiceRemark' => 'TAX_AND_SERVICE_REMARK',
    'GuaranteeLetterRemark' => 'GUARANTEE_LETTER_REMARK',
//Company Bank Account
    'BankName1' => 'BANK_NAME',
    'BankAccount1' => 'BANK_ACCOUNT',
    'HolderName1' => 'HOLDER_NAME',
    'BankName2' => 'BANK_NAME2',
    'BankAccount2' => 'BANK_ACCOUNT2',
    'HolderName2' => 'HOLDER_NAME2',
//Floor Plan
    'MinRoomWidth' => 'MIN_ROOM_WIDTH',
    'MinRoomHeight' => 'MIN_ROOM_HEIGHT',
    'LeftMargin' => 'LEFT_MARGIN',
    'TopMargin' => 'TOP_MARGIN',
    'TileColumn' => 'TILE_COLUMN',
    'TileDistance' => 'TILE_DISTANCE',
    'SnapGrid' => 'SNAP_GRID',
//Room Status Color
    'Reserved' => 'RESERVED',
    'Occupied' => 'OCCUPIED',
    'HouseUse' => 'HOUSE_USE',
    'Compliment' => 'COMPLIMENT',
    'OutOfOrder' => 'OUT_OF_ORDER',
    'OfficeUse' => 'OFFICE_USE',
    'UnderConstruction' => 'UNDER_CONSTRUCTION',
    'Available' => 'AVAILABLE',
//Keylock
    'KeylockVendor' => 'KEYLOCK_VENDOR',
    'PMSServiceAddress' => 'PMS_SERVICE_ADDRESS',
    'PMSServicePort' => 'PMS_SERVICE_PORT',
    'SureLockHotelID' => 'SURE_LOCK_HOTEL_ID',
    'KimaOperatorCode' => 'KIMA_OPERATOR_CODE',
    'VingCardKeyType' => 'VING_CARD_KEY_TYPE',
    'VingCardUserGroup' => 'VING_CARD_USER_GROUP',
    'VingCardSource' => 'VING_CARD_SOURCE',
    'VingCardDestination' => 'VING_CARD_DESTINATION',
    'BeTechPort' => 'BE_TECH_PORT',
    'BeTechReaderType' => 'BE_TECH_READER_TYPE',
    'BeTechDatabaseType' => 'BE_TECH_DATABASE_TYPE',
    'BeTechServerName' => 'BE_TECH_SERVER_NAME',
    'BeTechUserName' => 'BE_TECH_USER_NAME',
    'BeTechPassword' => 'BE_TECH_PASSWORD',
    'OnityDBType' => 'ONITY_DATABASE_TYPE',
    'OnityServerName' => 'ONITY_SERVER_NAME',
    'OnitySoftwareType' => 'ONITY_SOFTWARE_TYPE',
    'OnityPort' => 'ONITY_PORT',
    'SaflokToStation' => 'SAFLOK_TO_STATION',
    'SaflokFromStation' => 'SAFLOK_FROM_STATION',
    'SaflokRequestNumber' => 'SAFLOK_REQUEST_NUMBER',
    'SaflokPassword' => 'SAFLOK_PASSWORD',
    'SaflokEncoderStation' => 'SAFLOK_ENCODER_STATION',
    'VisionlinePMSAddress' => 'VISIONLINE_PMS_ADDRESS',
    'DownsAuthCode' => 'DOWNS_AUTH_CODE',
//PABX
    'PABXChargePerSecond' => 'CHARGE_PER_SECOND',
    'PABXAutoPostToFolio' => 'AUTO_CHARGE_TO_FOLIO',
    'PABXLANSMDRPassword' => 'LAN_SMDR_PASSWORD',
//Room Costing
    'DefaultStore' => 'DEFAULT_STORE',
//Other HK
    'VRVCRoomStatus' => 'VR_VC_ROOM_STATUS',
    'ShowRemarkOnRoomAvailability' => 'SHOW_REMARK_ON_ROOM_AVAILABILITY',
//IPTV
    'IPTVPassword' => 'IPTV_PASSWORD',
    'IPTVSubFolio' => 'IPTV_SUB_FOLIO',
    'IPTVAddress' => 'IPTV_ADDRESS',
//CCMS
    'CCMSSMUser' => 'SITE_MINDER_USER',
    'CCMSSMPassword' => 'SITE_MINDER_PASSWORD',
    'CCMSSMRequestorID' => 'SITE_MINDER_REQUESTOR_ID',
    'CCMSSMHotelCode' => 'SITE_MINDER_HOTEL_CODE',
    'CCMSSMWSDL' => 'SITE_MINDER_WSDL',
    'CCMSSMReservationAsAllotment' => 'SITE_MINDER_RESERVATION_AS_ALLOTMENT',
    'CCMSSMSynchronizeReservation' => 'SITE_MINDER_SYNCHRONIZE_RESERVATION',
    'CCMSSMSynchronizeAvailability' => 'SITE_MINDER_SYNCHRONIZE_AVAILABILITY',
    'CCMSSMSynchronizeRate' => 'SITE_MINDER_SYNCHRONIZE_RATE',
//Mikrotik
    'MikrotikVendor' => 'MIKROTIK_VENDOR',
    'MikrotikAddress' => 'MIKROTIK_ADDRESS',
    'MikrotikUser' => 'MIKROTIK_USER',
    'MikrotikPassword' => 'MIKROTIK_PASSWORD',
    'MikrotikHotspotServer' => 'MIKROTIK_HOTSPOT_SERVER',
    'MikrotikUserProfile' => 'MIKROTIK_USER_PROFILE',
    'MikrotikServiceAddress' => 'MIKROTIK_SERVICE_ADDRESS',
    'MikrotikAutoCreateUser' => 'MIKROTIK_AUTO_CREATE_USER',
    'MikrotikSameUserPassword' => 'MIKROTIK_SAME_USER_PASSWORD',
    'MikrotikAskForPassword' => 'MIKROTIK_ASK_FOR_PASSWORD',
    'MikrotikPasswordOption' => 'MIKROTIK_PASSWORD_OPTION',
//Notification
    'NotificationActive' => 'NOTIFICATION_ACTIVE',
    'NotificationDuration' => 'NOTIFICATION_DURATION',
    'NotificationDelay' => 'NOTIFICATION_DELAY',
    'NotificationWidth' => 'NOTIFICATION_WIDTH',
    'NotificationHeight' => 'NOTIFICATION_HEIGHT',
    'NotificationStyle' => 'NOTIFICATION_STYLE',
    'NotificationPosition' => 'NOTIFICATION_POSITION',
//Inventory
    'CostingMethod' => 'COSTING_METHOD'
];

// Table Name Tracking Data
    public static $tableName = [
        "acc_ap_ar",
        "acc_ap_ar_payment",
        "acc_ap_ar_payment_detail",
        "acc_ap_commission_payment",
        "acc_ap_commission_payment_detail",
        "acc_ap_no_show_payment",
        "acc_ap_no_show_payment_detail",
        "acc_cash_sale_recon",
        "acc_cfg_init_bank_account",
        "acc_close_month",
        "acc_close_year",
        "acc_const_bank_account_type",
        "acc_const_journal_group",
        "acc_const_journal_type",
        "acc_credit_card_recon",
        "acc_credit_card_recon_detail",
        "acc_foreign_cash",
        "acc_import_journal_log",
        "acc_journal",
        "acc_journal_detail",
        "acc_prepaid_expense",
        "acc_prepaid_expense_posted",
        "acc_report",
        "acc_report_default_field",
        "acc_report_group_field",
        "acc_report_grouping_field",
        "acc_report_order_field",
        "acc_report_template",
        "acc_report_template_field",
        "acc_user_group",
        "ast_cfg_init_shipping_address",
        "ast_const_purchase_request_status",
        "ast_const_store_requisition_status",
        "ast_report",
        "ast_report_default_field",
        "ast_report_group_field",
        "ast_report_grouping_field",
        "ast_report_order_field",
        "ast_report_template",
        "ast_report_template_field",
        "ast_user_group",
        "ast_user_sub_department",
        "audit_log",
        "ban_booking",
        "ban_cfg_init_seating_plan",
        "ban_cfg_init_theme",
        "ban_cfg_init_venue",
        "ban_cfg_init_venue_combine",
        "ban_cfg_init_venue_combine_detail",
        "ban_cfg_init_venue_group",
        "ban_const_booking_status",
        "ban_const_reservation_status",
        "ban_const_reservation_type",
        "ban_const_venue_location",
        "ban_report",
        "ban_report_default_field",
        "ban_report_group_field",
        "ban_report_grouping_field",
        "ban_report_order_field",
        "ban_report_template",
        "ban_report_template_field",
        "ban_reservation",
        "ban_reservation_charge",
        "ban_reservation_remark",
        "ban_user_group",
        "breakfast_list_temp",
        "budget_expense",
        "budget_fb",
        "budget_income",
        "budget_statistic",
        "cash_count",
        "cfg_init_account",
        "cfg_init_account_sub_group",
        "cfg_init_bed_type",
        "cfg_init_booking_source",
        "cfg_init_card_bank",
        "cfg_init_card_type",
        "cfg_init_city",
        "cfg_init_company_type",
        "cfg_init_competitor_category",
        "cfg_init_continent",
        "cfg_init_country",
        "cfg_init_credit_card_charge",
        "cfg_init_currency",
        "cfg_init_currency_nominal",
        "cfg_init_custom_lookup_field01",
        "cfg_init_custom_lookup_field02",
        "cfg_init_custom_lookup_field03",
        "cfg_init_custom_lookup_field04",
        "cfg_init_custom_lookup_field05",
        "cfg_init_custom_lookup_field06",
        "cfg_init_custom_lookup_field07",
        "cfg_init_custom_lookup_field08",
        "cfg_init_custom_lookup_field09",
        "cfg_init_custom_lookup_field10",
        "cfg_init_custom_lookup_field11",
        "cfg_init_custom_lookup_field12",
        "cfg_init_department",
        "cfg_init_guest_type",
        "cfg_init_id_card_type",
        "cfg_init_is_fb_sub_department_group",
        "cfg_init_is_fb_sub_department_group_detail",
        "cfg_init_journal_account",
        "cfg_init_journal_account_category",
        "cfg_init_journal_account_sub_group",
        "cfg_init_language",
        "cfg_init_loan_item",
        "cfg_init_market",
        "cfg_init_market_category",
        "cfg_init_marketing",
        "cfg_init_member_point_type",
        "cfg_init_nationality",
        "cfg_init_owner",
        "cfg_init_package",
        "cfg_init_package_breakdown",
        "cfg_init_package_business_source",
        "cfg_init_payment_type",
        "cfg_init_phone_book_type",
        "cfg_init_printer",
        "cfg_init_regency",
        "cfg_init_reservation_mark",
        "cfg_init_room",
        "cfg_init_room_allotment_type",
        "cfg_init_room_amenities",
        "cfg_init_room_boy",
        "cfg_init_room_rate",
        "cfg_init_room_rate_breakdown",
        "cfg_init_room_rate_business_source",
        "cfg_init_room_rate_category",
        "cfg_init_room_rate_currency",
        "cfg_init_room_rate_dynamic",
        "cfg_init_room_rate_sub_category",
        "cfg_init_room_type",
        "cfg_init_room_unavailable_reason",
        "cfg_init_room_view",
        "cfg_init_state",
        "cfg_init_sub_department",
        "cfg_init_tax_and_service",
        "cfg_init_title",
        "cfg_init_voucher_reason",
        "cm_update",
        "company",
        "competitor",
        "competitor_data",
        "configuration",
        "const_account_group",
        "const_budget_type",
        "const_charge_frequency",
        "const_charge_type",
        "const_commission_type",
        "const_customer_display_vendor",
        "const_department_type",
        "const_folio_status",
        "const_folio_type",
        "const_forecast_day",
        "const_forecast_month",
        "const_foreign_cash_table_id",
        "const_guest_status",
        "const_image",
        "const_iptv_vendor",
        "const_journal_account_group",
        "const_journal_account_sub_group_type",
        "const_journal_account_type",
        "const_journal_prefix",
        "const_keylock_vendor",
        "const_member_type",
        "const_mikrotik_vendor",
        "const_notification_type",
        "const_other_icon",
        "const_otp_status",
        "const_payment_group",
        "const_report_font",
        "const_report_format",
        "const_reservation_status",
        "const_room_block_status",
        "const_room_status",
        "const_sms_destination_type",
        "const_sms_repeat_type",
        "const_statistic_account",
        "const_system",
        "const_transaction_type",
        "const_voucher_status",
        "const_voucher_status_approve",
        "const_voucher_status_sold",
        "const_voucher_type",
        "contact_person",
        "cor_cfg_init_unit",
        "cor_report",
        "cor_report_default_field",
        "cor_report_group_field",
        "cor_report_grouping_field",
        "cor_report_order_field",
        "cor_report_template",
        "cor_report_template_field",
        "cor_user_group",
        "credit_card",
        "data_analysis",
        "data_analysis_query",
        "data_analysis_query_list",
        "events",
        "fa_cfg_init_item",
        "fa_cfg_init_item_category",
        "fa_cfg_init_location",
        "fa_cfg_init_manufacture",
        "fa_const_depreciation_type",
        "fa_const_item_condition",
        "fa_const_location_type",
        "fa_depreciation",
        "fa_list",
        "fa_location_history",
        "fa_purchase_order",
        "fa_purchase_order_detail",
        "fa_receive",
        "fa_receive_detail",
        "fa_repair",
        "fa_revaluation",
        "failed_jobs",
        "fb_statistic",
        "folio",
        "folio_list",
        "folio_routing",
        "forecast_in_house_change_pax",
        "forecast_monthly_day",
        "forecast_monthly_day_previous",
        "grid_properties",
        "guest_breakdown",
        "guest_deposit",
        "guest_deposit_tax",
        "guest_detail",
        "guest_extra_charge",
        "guest_extra_charge_breakdown",
        "guest_group",
        "guest_in_house",
        "guest_in_house_breakdown",
        "guest_loan_item",
        "guest_message",
        "guest_profile",
        "guest_scheduled_rate",
        "guest_to_do",
        "hotel_information",
        "inv_cfg_init_item",
        "inv_cfg_init_item_category",
        "inv_cfg_init_item_category_other_cogs",
        "inv_cfg_init_item_category_other_cogs2",
        "inv_cfg_init_item_category_other_expense",
        "inv_cfg_init_item_group",
        "inv_cfg_init_item_uom",
        "inv_cfg_init_market_list",
        "inv_cfg_init_return_stock_reason",
        "inv_cfg_init_store",
        "inv_cfg_init_uom",
        "inv_close_log",
        "inv_cost_recipe",
        "inv_costing",
        "inv_costing_detail",
        "inv_opname",
        "inv_production",
        "inv_purchase_order",
        "inv_purchase_order_detail",
        "inv_purchase_request",
        "inv_purchase_request_detail",
        "inv_receive",
        "inv_receive_detail",
        "inv_return_stock",
        "inv_stock_transfer",
        "inv_stock_transfer_detail",
        "inv_store_requisition",
        "inv_store_requisition_detail",
        "invoice",
        "invoice_item",
        "invoice_payment",
        "log",
        "log_backup",
        "log_keylock",
        "log_mode",
        "log_shift",
        "log_special_access",
        "log_user",
        "log_user_action",
        "log_user_action_group",
        "lost_and_found",
        "market_statistic",
        "member",
        "member_gift",
        "member_point",
        "member_point_redeem",
        "migrations",
        "notification",
        "oauth_access_tokens",
        "oauth_auth_codes",
        "oauth_clients",
        "oauth_personal_access_clients",
        "oauth_refresh_tokens",
        "one_time_password",
        "pabx_smdr",
        "password_resets",
        "phone_book",
        "pos_captain_order",
        "pos_captain_order_transaction",
        "pos_cfg_init_discount_limit",
        "pos_cfg_init_market",
        "pos_cfg_init_member_outlet_discount",
        "pos_cfg_init_member_outlet_discount_detail",
        "pos_cfg_init_member_product_discount",
        "pos_cfg_init_outlet",
        "pos_cfg_init_payment_group",
        "pos_cfg_init_product",
        "pos_cfg_init_product_category",
        "pos_cfg_init_product_group",
        "pos_cfg_init_room_boy",
        "pos_cfg_init_table",
        "pos_cfg_init_table_type",
        "pos_cfg_init_tenan",
        "pos_cfg_init_waitress",
        "pos_check",
        "pos_check_transaction",
        "pos_const_check_type",
        "pos_const_compliment_type",
        "pos_const_discount",
        "pos_const_time_segment",
        "pos_information",
        "pos_iptv_menu_order",
        "pos_member",
        "pos_product_costing",
        "pos_report",
        "pos_report_default_field",
        "pos_report_group_field",
        "pos_report_grouping_field",
        "pos_report_order_field",
        "pos_report_template",
        "pos_report_template_field",
        "pos_reservation",
        "pos_reservation_table",
        "pos_table_unavailable",
        "pos_user_group",
        "pos_user_group_outlet",
        "proforma_invoice_detail",
        "receipt",
        "report",
        "report_custom",
        "report_custom_favorite",
        "report_default_field",
        "report_group_field",
        "report_grouping_field",
        "report_order_field",
        "report_pivot_temp",
        "report_room_rate_structure_temp",
        "report_room_sales",
        "report_template",
        "report_template_field",
        "reservation",
        "reservation_extra_charge",
        "reservation_extra_charge_breakdown",
        "reservation_scheduled_rate",
        "room_allotment",
        "room_statistic",
        "room_status",
        "room_unavailable",
        "room_unavailable_history",
        "sms_event",
        "sms_outbox",
        "sms_schedule",
        "sub_folio",
        "sub_folio_group",
        "sub_folio_grouping",
        "sub_folio_tax",
        "temp_sub_folio_breakdown1",
        "temp_sub_folio_correction_breakdown",
        "transaction_list",
        "transaction_list_tax",
        "user",
        "user_group",
        "users",
        "voucher",
        "working_shift"
    ];

    public static $logUserAction = [
        //Reservation
        'InsertReservation' => 10101,
        'VoidReservation' => 10102,
        'CheckInReservation' => 10103,
        'CancelReservation' => 10104,
        'NoShowReservation' => 10105,
        'InsertDeposit' => 10106,
        'VoidDeposit' => 10107,
        'CorrectDeposit' => 10108,
        'RefundDeposit' => 10109,
        'TransferDeposit' => 10110,
        'InsertReservationScheduledRate' => 10151,
        'UpdateReservationScheduledRate' => 10152,
        'DeleteReservationScheduledRate' => 10153,
        'InsertReservationExtraCharge' => 10154,
        'UpdateReservationExtraCharge' => 10155,
        'DeleteReservationExtraCharge' => 10156,
        'InsertReservationExtraChargeBreakdown' => 10157,
        'UpdateReservationExtraChargeBreakdown' => 10158,
        'DeleteReservationExtraChargeBreakdown' => 10159,
        //Update Reservation Stay Information
        'URSIArrival' => 10201,
        'URSINights' => 10202,
        'URSIDeparture' => 10203,
        'URSIAdult' => 10204,
        'URSIChild' => 10205,
        'URSIRoomType' => 10206,
        'URSIRoom' => 10207,
        'URSIRoomRate' => 10208,
        'URSIBusinessSource' => 10209,
        'URSICommissionType' => 10210,
        'URSICommissionValue' => 10211,
        'URSIWeekdayRate' => 10212,
        'URSIWeekendRate' => 10213,
        'URSIDiscount' => 10214,
        'URSIPaymentType' => 10215,
        'URSIMarket' => 10216,
        'URSIBillInstruction' => 10217,
        'URSICurrency' => 10218,
        'URSIExchangeRate' => 10219,
        //Update Reservation Personal Information
        'URPITitle' => 10301,
        'URPIFullName' => 10302,
        'URPIReservationBy' => 10303,
        'URPIStreet' => 10304,
        'URPICity' => 10305,
        'URPICountry' => 10306,
        'URPIState' => 10307,
        'URPIPostCode' => 10308,
        'URPIPhone1' => 10309,
        'URPIPhone2' => 10310,
        'URPIFax' => 10311,
        'URPIEmail' => 10312,
        'URPIWebsite' => 10313,
        'URPICompany' => 10314,
        'URPIGuestType' => 10315,
        'URPIIDCardType' => 10316,
        'URPIIDCardNumber' => 10317,
        'URPIBirthdayPlace' => 10318,
        'URPIBirthdate' => 10319,
        //Update Reservation General Information
        'URGIGroup' => 10401,
        'URGIDocumentNumber' => 10402,
        'URGIFlightNumber' => 10403,
        'URGIFlightArrival' => 10404,
        'URGIFlightDeparture' => 10405,
        'URGINotes' => 10406,
        'URGIHKNotes' => 10407,
        'URGIMarketing' => 10408,
        'URGITAVoucherNumber' => 10409,
        //Group Reservation
        'InsertGroupReservation' => 20101,
        'UpdateGroupReservation' => 20102,
        'DeleteGroupReservation' => 20103,
        //Folio
        'WalkIn' => 30101,
        'InsertMasterFolio' => 30102,
        'InsertDeskFolio' => 30103,
        'InsertFolioScheduledRate' => 30104,
        'UpdateFolioScheduledRate' => 30105,
        'DeleteFolioScheduledRate' => 30106,
        'InsertFolioExtraCharge' => 30107,
        'UpdateFolioExtraCharge' => 30108,
        'DeleteFolioExtraCharge' => 30109,
        'InsertFolioExtraChargeBreakdown' => 30110,
        'UpdateFolioExtraChargeBreakdown' => 30111,
        'DeleteFolioExtraChargeBreakdown' => 30112,
        'InsertTransaction' => 30113,
        'VoidTransaction' => 30114,
        'CorrectTransaction' => 30115,
        'TransferTransaction' => 30116,
        'RoutingFolio' => 30117,
        'ReturnTransfer' => 30118,
        'RemoveRouting' => 30119,
        'MoveRoom' => 30120,
        'SwitchRoom' => 30121,
        'InsertMessage' => 30122,
        'UpdateMessage' => 30123,
        'DeleteMessage' => 30124,
        'MarkAsDeliveredMessage' => 30125,
        'MarkAsUndeliveredMessage' => 30126,
        'InsertToDo' => 30127,
        'UpdateToDo' => 30128,
        'DeleteToDo' => 30129,
        'MarkAsDoneToDo' => 30130,
        'MarkAsNotDoneToDo' => 30131,
        'CancelCheckIn' => 30132,
        'CheckOutFolio' => 30133,
        'CancelCheckOut' => 30134,
        'ComplimentGuest' => 30135,
        'HouseUseGuest' => 30136,
        'DefaultGuest' => 30137,
        'UpdateFolioVoucher' => 30138,
        'InsertVoucherPayment' => 30139,
        'IssuedCard' => 30161,
        'ReplaceCard' => 30162,
        'EraseCard' => 30163,
        'DeactivateWithoutCard' => 30164,
        'ForceEraseCard' => 30165,
        //Update Folio Stay Information
        'UFSIArrival' => 30201,
        'UFSINights' => 30202,
        'UFSIDeparture' => 30203,
        'UFSIAdult' => 30204,
        'UFSIChild' => 30205,
        'UFSIRoomType' => 30206,
        'UFSIRoom' => 30207,
        'UFSIRoomRate' => 30208,
        'UFSIBusinessSource' => 30209,
        'UFSICommissionType' => 30210,
        'UFSICommissionValue' => 30211,
        'UFSIWeekdayRate' => 30212,
        'UFSIWeekendRate' => 30213,
        'UFSIDiscount' => 30214,
        'UFSIPaymentType' => 30215,
        'UFSIMarket' => 30216,
        'UFSIBillInstruction' => 30217,
        'UFSICurrency' => 30218,
        'UFSIExchangeRate' => 30219,
        //Update Folio Personal Information
        'UFPITitle' => 30301,
        'UFPIFullName' => 30302,
        'UFPIStreet' => 30303,
        'UFPICity' => 30304,
        'UFPICountry' => 30305,
        'UFPIState' => 30306,
        'UFPIPostCode' => 30307,
        'UFPIPhone1' => 30308,
        'UFPIPhone2' => 30309,
        'UFPIFax' => 30310,
        'UFPIEmail' => 30311,
        'UFPIWebsite' => 30312,
        'UFPICompany' => 30313,
        'UFPIGuestType' => 30314,
        'UFPIIDCardType' => 30315,
        'UFPIIDCardNumber' => 30316,
        'UFPIBirthdayPlace' => 30317,
        'UFPIBirthdate' => 30318,
        //Update Folio General Information
        'UFGIGroup' => 30401,
        'UFGIDocumentNumber' => 30402,
        'UFGIFlightNumber' => 30403,
        'UFGIFlightArrival' => 30404,
        'UFGIFlightDeparture' => 30405,
        'UFGINotes' => 30406,
        'UFGIHKNotes' => 30407,
        'UFGIMarketing' => 30408,
        'UFGITAVoucherNumber' => 30409,
        //Member Voucher Gift
        'MVInsertMember' => 30501,
        'MVUpdateMember' => 30502,
        'MVDeleteMember' => 30503,
        'MVRedeemMemberPoint' => 30504,
        'MVInsertVoucher' => 30511,
        'MVDeleteVoucher' => 30512,
        'MVApproveVoucher' => 30513,
        'MVNotApproveVoucher' => 30514,
        'MVUnapproveVoucher' => 30519,
        'MVSoldVoucher' => 30515,
        'MVRedeemVoucher' => 30516,
        'MVComplimentVoucher' => 30517,
        'MVUnsoldVoucher' => 30518,
        //House Keeping
        'ReadyRoom' => 40101,
        'CleanRoom' => 40102,
        'DirtyRoom' => 40103,
        'OutOfOrder' => 40104,
        'OfficeUse' => 40105,
        'UnderConstruction' => 40107,
        'DontDisturb' => 40108,
        'DoubleLock' => 40109,
        'SleepOut' => 40110,
        'PleaseClean' => 40114,
        'InsertRoomCosting' => 40111,
        'DeleteRoomCostingTransfer' => 40112,
        'DeleteRoomCosting' => 40113,
        //Report
        'InsertReportTemplate' => 50101,
        'UpdateReportTemplate' => 50102,
        'DeleteReportTemplate' => 50103,
        'SetDefaultReportTemplate' => 50104,
        //Configuration
        'CompanyInformation' => 60101,
        'Configuration' => 60102,
        'InsertMasterData' => 60103,
        'UpdateMasterData' => 60104,
        'DeleteMasterData' => 60105,
        'ModifyFloorPlan' => 60106,
        //Accounting Tool
        'InsertReceipt' => 43107,
        'UpdateReceipt' => 43108,
        'DeleteReceipt' => 43109,
        'InsertIncomeBudget' => 43113,
        'UpdateIncomeBudget' => 43114,
        'DeleteIncomeBudget' => 43115,
        'InsertBudgetStatistic' => 43119,
        'UpdateBudgetStatistic' => 43120,
        'DeleteBudgetStatistic' => 43121,
        //Account Payable
        'InsertAPRefundDepositPayment' => 43207,
        'UpdateAPRefundDepositPayment' => 43208,
        'DeleteAPRefundDepositPayment' => 4209,
        'InsertAPCommissionPayment' => 43210,
        'UpdateAPCommissionPayment' => 43211,
        'DeleteAPCommissionPayment' => 43212,
        //Account Receivable
        'InsertInvoiceCityLedger' => 43307,
        'UpdateInvoiceCityLedger' => 43308,
        'DeleteInvoiceCityLedger' => 43309,
        'InsertPaymentInvoiceCityLedger' => 43310,
        'UpdatePaymentInvoiceCityLedger' => 43311,
        'DeletePaymentInvoiceCityLedger' => 43312,
        'InsertBankReconciliation' => 43313,
        'UpdateBankReconciliation' => 43314,
        'DeleteBankReconciliation' => 43315,
        'PrintInvoice' => 43316,
        //User Setting
        'InsertUser' => 70101,
        'UpdateUser' => 70102,
        'DeleteUser' => 70103,
        'InsertUserGroup' => 70104,
        'UpdateUserGroup' => 70105,
        'DeleteUserGroup' => 70106,
        //Database
        'BackupDatabase' => 80101,
        'RestoreDatabase' => 80102,
        'OptimizingDatabase' => 80103,
        //Login
        'Login' => 90101,
        'Logout' => 90102,
        'ChangePassword' => 90103,
        'LoginDenied' => 90104
    ];

    public static $specialAccessList = [
        'Unlock Reservation',
        'Void Reservation',
        'Void Deposit',
        'Correct Deposit',
        'Decrease Stay',
        'Scheduled Rate',
        'Breakdown',
        'Extra Charge',
        'Compliment Guest',
        'House Use Guest',
        'Move Room',
        'Void Sub Folio',
        'Correct Sub Folio',
        'Cancel Check In',
        'Cancel Check Out',
        'Create Master Folio',
        'Print More Invoice',
        'Modify Closed Journal',
        'Transfer to Desk Folio',
        'Transfer to Master Folio',
        'Business Source',
        'Override Rate/Discount'
    ];

    public static function weekendDay($day) {
        $result = false;
        if($day == 'Friday'){
            $result = ConfigurationController::value(null, VariableGlobal::$configurationCategory['WeekendDay'], VariableGlobal::$configurationName['FridayAsWeekend']);
        } else if($day == 'Saturday'){
            $result = ConfigurationController::value(null, VariableGlobal::$configurationCategory['WeekendDay'], VariableGlobal::$configurationName['SaturdayAsWeekend']);
        } else if( $day == 'Sunday' ){
            $result = ConfigurationController::value(null, VariableGlobal::$configurationCategory['WeekendDay'], VariableGlobal::$configurationName['SundayAsWeekend']);
        }

        return HelperController::trueFalseString($result);
    }

    public static function useChildRate() {
            $result = ConfigurationController::value(null, VariableGlobal::$configurationCategory['General'], VariableGlobal::$configurationName['UseChildRate']);

        return HelperController::trueFalseString($result);
    }

    public static function VRVCRoomStatus() {
        $result = ConfigurationController::value(null, VariableGlobal::$configurationCategory['OtherHK'], VariableGlobal::$configurationName['VRVCRoomStatus']);

    return HelperController::trueFalseString($result);
}

    public static function postDiscount() {
        $result = ConfigurationController::value(null, VariableGlobal::$configurationCategory['Reservation'], VariableGlobal::$configurationName['PostDiscount']);

        return HelperController::trueFalseString($result);
    }

    public static function globalAccount($accountName){
        $result = ConfigurationController::value(null, VariableGlobal::$configurationCategory['GlobalAccount'], $accountName );
        return $result;
    }

    public static function defaultVariable($accountName){
        $result = ConfigurationController::value(null, VariableGlobal::$configurationCategory['DefaultVariable'], $accountName );
        return $result;
    }

    public static function globalAccountGroup($accountName){
        $result = ConfigurationController::value(null, VariableGlobal::$configurationCategory['GlobalAccount'], $accountName );
        return $result;
    }

    public static function globalJournalAccount($accountName){
        $result = ConfigurationController::value(null, VariableGlobal::$configurationCategory['GlobalJournalAccount'], $accountName );
        return $result;
    }

    public static function globalSubDepartment($accountName){
        $result = ConfigurationController::value(null, VariableGlobal::$configurationCategory['GlobalSubDepartment'], $accountName );
        return $result;
    }

    public static function allowZeroAmount(){
        $result = ConfigurationController::value(null, VariableGlobal::$configurationCategory['Folio'], GlobalVariableController::$configurationName['AllowZeroAmount'] );
        return HelperController::trueFalseString($result);
    }


}
