import { formConfig } from './formConfig';

export default {
    global: {
        // Const Program Variable
        constProgramVariable: {
            defaultSystemCode: 'H',
        },

        formConfig,

        formType: {
            reservation: 'R',
            guestInHouse: 'I',
            folioHistory: 'H',
            masterFolio: 'M',
            deskFolio: 'D',
            housekeeping: 'HK',
            availability: 'A',
            roomAvailability: 'RA',
            transaction: 'T',
            lostAndFound: 'LF',
            arCityLedger: 'CL',
            arCityLedgerInvoice: 'CLI',
            bankTransaction: 'BT',
            bankReconciliation: 'BR',
            apCommissionAndOther: 'APC',
            apRefundDeposit: 'APR',
            incomeBudget: 'IB',
            budgetStatistic: 'BS',
        },
        logUserAction: {
            // Folio
            voidTransaction: '30114',
            transferTransaction: '30116',
            moveRoom: '30120',
            // House Keeping
            readyRoom: '40101',
            cleanRoom: '40102',
            dirtyRoom: '40103',
        },
        // UserInfo
        userInfo: {
            id: 0,
            code: '',
            email: '',
            groupCode: '',
        },
        // Mode Data
        modeData: {
            insert: 0,
            edit: 1,
            tracking: 2,
            delete: 3,
            duplicate: 4,
        },
        modeBreakdown: {
            insert: '00',
            edit: '11',
            tracking: '22',
        },
        modeBusinessSource: {
            insert: '000',
            edit: '111',
            tracking: '222',
        },
        modeCurrency: {
            insert: '0000',
            edit: '1111',
            tracking: '2222',
        },
        modeDataName: {
            insert: 'Insert ',
            edit: 'Edit ',
            tracking: 'Tracking Data ',
        },
        modeDeposit: {
            cash: 'd1',
            card: 'd2',
            other: 'd3',
            refund: 'd4',
            directBill: 'd5',
            tracking: 'd6'
        },
        roomStatus: {
            ready: 'R',
            clean: 'C',
            dirty: 'D',
            dontDisturb: 'DD',
            doubleLock: 'DL',
            houseUse: 'H',
            occupied: 'O',
            occupiedClean: 'OC',
            occupiedDirty: 'OD',
            officeUse: 'OF',
            outOfOrder: 'OO',
            compliment: 'P',
            pleaseClean: 'PC',
            sleepOut: 'SO',
            underConstruction: 'UC',
            vacant: 'V',
        },
        roomBlockStatus: {
            generalCleaning: 'G',
            showingRoom: 'S',
        },

        folioType: {
            guestFolio: 'F',
            masterFolio: 'M',
            deskFolio: 'D',
        },

        folioStatus: {
            open: 'O',
            closed: 'C',
            cancelCheckIn: 'I',
        },

        hkMode: {
            roomAvailable: 'room available',
            roomUnavailable: 'room unavailable',
            roomBlock: 'room block',
        },
        reasonType: {
            reservation: 'R',
            void: 'V',
            correction: 'C',
        },
        reservationStatus: {
            waitList: 'W',
            new: 'N',
            checkIn: 'I',
            checkOut: 'O',
            cancel: 'C',
            noShow: 'S',
            void: 'V',
        },
        groupAccount: {
            charge: '1',
            payment: '2',
            taxService: '3',
            transfer: '4',
        },

        transactionType: {
            debit: 'D',
            credit: 'C',
        },

        subGroupAccount: {
            room: 'ROOM',
            foodAndBeverage: 'FBCH',
            roomFacilities: 'RMFC',
            generalCharge: 'GNRL',
            rentCharge: 'RENT',
            sales: 'SALE',
            accountPayable: 'ACPY',
            otherCharge: 'OTCH',
            cashPayment: 'PYMT',
            creditOrDebitCard: 'CRDB',
            bankTransfer: 'BKTR',
            accountReceiveable: 'ACRV',
            compliment: 'CMPL',
            discount: 'DSCN',
            otherPayment: 'OTPY',
            taxService: 'TXSV',
            transfer: 'TRAN',
        },

        transfer: {
            combineAll: 1,
            transferAll: 2,
            transferSelected: 3,
        },

        subFolioGroup: ['A', 'B', 'C', 'D'],

        subFolio: {
            A: 'A',
            B: 'B',
            C: 'C',
            D: 'D',
        },

        _CRYPTO_KEY: 'cakrat3ndadOs',

        solutionCriticalErrorDayendClose: {
            autoAssign: 'Auto Assign',
            checkIn: 'Check In',
            cancel: 'Cancel',
            changeArrival: 'Change Arrival',
            noShow: 'No Show',
            checkOut: 'Check Out',
            extend: 'Extend',
            openPos: 'Open Pos',
            autoPosting: 'Auto Posting',
            showFolio: 'Show Folio',
            showDeposit: 'Show Deposit',
            unsetWaitList: 'Unset Wait List',
        },

        mt: [
            '01',
            '02',
            '03',
            '04',
            '05',
            '06',
            '07',
            '08',
            '09',
            '10',
            '11',
            '12',
        ],
        yr: [
            '19',
            '20',
            '21',
            '22',
            '23',
            '24',
            '25',
            '26',
            '27',
            '28',
            '29',
            '30',
        ],

        perfectScrollbarSettings: {
            // perfectScrollbar settings
            maxScrollbarLength: 100,
            wheelSpeed: 1,
            swipeEasing: true,
        },
        // Dialog Global
        dialog: {
            typeDialog: 'confirm', // alert & confirm
            isAddHeaderCloseButton: true,
        },
        //
        notifPosition: 'top-center',
        scaleLoadingMainLayout: 1,
        scaleLoadingContainer: 0.7,
        scaleLoadingButton: 0.4,
        // Data Grid
        dataGridShowColumnLine: false,
        dataGridShowRowLine: true,
        dataGridShowBorder: true,
        dataGridRowAlternationEnabled: false,
        // Ag grid
        rowIndexBeforeDelete: 0,
        themeAgGrid: 'ag-theme-balham',
        styleAgGridFrame: 'width: 100%; height: 550px;',
        styleAgGridFrame3: 'width: 100%; height: 450px;',
        styleAgGridFrame2: 'width: 100%; height: 350px;',
        styleAgGridFrame1: 'width: 100%; height: 250px;',
        styleAgGridFrame0: 'width: 100%; height: 200px;',
        limitDefaultPageSize: 1000,
        paginationDataPerPage: 100,
        rowHeightReservation: 33,
        rowHeightDefault: 30,
        buttonColor: {
            cancel: 'grey',
            back: 'black',
            close: 'grey',
            save: 'primary',
            insert: 'primary',
            ok: 'primary',
            yes: 'primary',
            no: 'danger',
            checkIn: 'primary',
            delete: 'danger',
            createMasterFolio: 'success',
            addRoutingAccount: 'success',
        },
        iconActionColor: {
            menuColor: 'warning',
            editColor: 'success',
            correctionColor: 'primary',
            deleteColor: 'danger',
        },
        animatedRows: true,
        defColDef: {
            sortable: true,
            resizable: true,
            filter: true,
            editable: false,
            checkboxSelection: false,
            menuTabs: ['filterMenuTab'],
            enableRowGroup: true, // AG GRID PRO
            // enablePivot: true, //AG GRID PRO
            // enableValue: true, //AG GRID PRO
        },
        colDef1: {
            sortable: true,
            resizable: true,
            editable: false,
            // menuTabs: ['filterMenuTab'],
            enableRowGroup: false, // AG GRID PRO
        },

        // Stimulsoft Dashboard Setting
        stimulsoftReportSetting: {
            fullScreenMode: true,
            scrollbarsMode: true,
            showTooltips: false,
            showDesignButton: false,
            showAboutButton: false,
            // export
            showExportToPdf: false,
            showExportToDocument: false,
            showExportToHtml: false,
            showExportToHtml5: false,
            showExportToExcel2007: false,
            // toolbar
            showOpenButton: false,
            showPrintButton: true,
            showSaveButton: false,
            showSendEmailButton: false,
        },

        stimulsoftReportFileDirectory: {
            // Report List
            pathReport: '../storage/reports/',
            // Form Report
            registrationFormReservation:
                '../storage/reports/RegistrationFormReservation.mrt',
            registrationFormInHouse:
                '../storage/reports/RegistrationFormInHouse.mrt',
            cashierReport: '../storage/reports/CashierReport.mrt',
            receipt: '../storage/reports/Receipt.mrt',
            receiptDeposit: '../storage/reports/ReceiptDeposit.mrt',
            receiptDepositRefund: '../storage/reports/ReceiptDepositRefund.mrt',
            receiptFolio: '../storage/reports/ReceiptFolio.mrt',
            receiptFolioRefund: '../storage/reports/ReceiptFolioRefund.mrt',
            proformaInvoice: '../storage/reports/ProformaInvoice.mrt',
            proformaInvoiceDetail: '../storage/reports/ProformaInvoiceDetail.mrt',
            confirmationLetter: '../storage/reports/ConfirmationLetter.mrt',
            folio: '../storage/reports/Folio.mrt',
            roomCheckList: '../storage/reports/HousekeepingCheckList.mrt',

            cityLedgerInvoice: '../storage/reports/CityLedgerInvoice.mrt',
            invoicePaymentReceive: '../storage/reports/InvoicePaymentReceive.mrt',
        },

        reportList: {
            reservationList: 1001,
            waitListReservation: 1011,
            cancelledReservation: 1002,
            noShowReservation: 1003,
            voidedReservation: 1004,
            groupReservation: 1005,
            expectedArrival: 1006,
            arrivalList: 1007,
            samedayReservation: 1008,
            advancedPaymentDeposit: 1009,
            balanceDeposit: 1010,
            currentInHouse: 1501,
            guestInHouse: 1502,
            guestInHouseListing: 1508,
            guestInHousebyBusinessSource: 1503,
            guestInHousebyMarket: 1504,
            guestInHousebyBookingSource: 1510,
            guestInHousebyGuestType: 1505,
            guestInHousebyCountry: 1506,
            guestInHousebyState: 1507,
            guestInHousebyCity: 1509,
            guestInHousebyNationality: 1516,
            guestList: 1517,
            guestInHouseForecast: 1513,
            repeaterGuest: 1514,
            folioList: 1515,
            masterFolio: 1511,
            deskFolio: 1512,
            incognitoGuest: 1520,
            complimentGuest: 1521,
            houseUseGuest: 1522,
            earlyCheckIn: 1523,
            dayUse: 1524,
            earlyDeparture: 1525,
            expectedDeparture: 1526,
            extendedDeparture: 1527,
            departureList: 1528,
            actualDepartureGuestList: 1529,
            folioTransaction: 1540,
            dailyFolioTransaction: 1541,
            monthlyFolioTransaction: 1542,
            yearlyTransaction: 1543,
            chargeList: 1544,
            dailyChargeList: 1545,
            monthlyChargeList: 1546,
            yearlyChargeList: 1547,
            cashierReport: 1548,
            cashierReportReprint: 1585,
            cashSummaryReport: 1587,
            paymentBySubDepartment: 1567,
            paymentByAccount: 1568,
            paymentList: 1549,
            dailyPaymentList: 1550,
            monthlyPaymentList: 1551,
            yearlyPaymentList: 1552,
            exportCSVbyDepartureDate: 1560,
            packageSales: 1586,
            guestLedger: 1561,
            guestDeposit: 1562,
            guestAccount: 1563,
            dailySales: 1564,
            voidList: 1582,
            dailyRevenueReport: 1565,
            dailyRevenueReportSummary: 1566,
            revenueBySubDepartment: 1569,
            folioOpenBalance: 1580,
            transactionByStaff: 1588,
            taxBreakdownDetailed: 1589,
            todayRoomRevenueBreakDown: 1590,
            correction: 1581,
            cancelCheckIn: 1583,
            lostandFound: 1584,
            cancelCheckOut: 1591,
            member: 1701,
            voucher: 1702,
            voucherSRC: 1703,
            roomList: 2001,
            roomType: 2002,
            roomRate: 2003,
            roomRateBreakdown: 2021,
            roomRateStructure: 2024,
            package: 2022,
            packageBreakdown: 2023,
            roomCountSheet: 2004,
            roomCountSheetByBuildingFloorRoomType: 2011,
            roomCountSheetByRoomTypeBedType: 2012,
            roomUnavailable: 2005,
            roomSales: 2006,
            roomSalesbyRoomNumber: 2013,
            roomRevenue: 2025,
            roomHistory: 2007,
            roomTypeAvailability: 2008,
            roomTypeAvailabilityDetail: 2009,
            roomStatus: 2010,
            sales: 2501,
            salesSummary: 2502,
            frequentlySales: 2503,
            captainOrderList: 2504,
            cancelledCaptainOrder: 2505,
            cancelledCaptainOrderDetail: 2507,
            voidedCheckList: 2506,
            breakfastControl: 2508,
            guestProfile: 3001,
            frequentlyGuest: 3002,
            company: 3003,
            phoneBook: 3004,
            contractRate: 3501,
            eventList: 3502,
            reservationChart: 3503,
            reservationGraphic: 3504,
            occupiedGraphic: 3505,
            occupiedbyBusinessSourceGraphic: 3506,
            occupiedbyMarketGraphic: 3507,
            occupiedbyGuestTypeGraphic: 3508,
            occupiedbyCountryGraphic: 3509,
            occupiedbyStateGraphic: 3510,
            occupancyGraphic: 3511,
            roomAvailabilityGraphic: 3531,
            roomUnvailabilityGraphic: 3532,
            revenueGraphic: 3533,
            paymentGraphic: 3534,
            dailyStatisticReport: 3546,
            roomStatistic: 3535,
            dailyFlashReport: 3544,
            roomProduction: 3539,
            otaProductivity: 3540,
            marketStatistic: 3542,
            dailyHotelCompetitor: 3545,
            fbStatistic: 3538,
            guestForecastReport: 3536,
            guestForecastComparison: 3543,
            guestForecastReportYearly: 3541,
            cityLedgerContributionAnalysis: 3537,
            rateCodeAnalisys: 3547,
            salesContributionAnalysis: 3548,
            leadList: 3601,
            taskList: 3602,
            proposalList: 3603,
            activityLog: 3604,
            salesActivityDetail: 3605,
            cityLedgerList: 4001,
            cityLedgerAgingReport: 4002,
            cityLedgerAgingReportDetail: 4003,
            cityLedgerInvoice: 4004,
            cityLedgerInvoiceDetail: 4005,
            cityLedgerInvoicePayment: 4006,
            cityLedgerInvoiceMutation: 4007,
            bankTransactionList: 4009,
            bankTransactionAgingReport: 4010,
            bankTransactionAgingReportDetail: 4011,
            bankReconciliation: 4008,
            bankTransactionMutation: 4012,
            apRefundDepositList: 5001,
            apRefundDepositAgingReport: 5002,
            apRefundDepositAgingReportDetail: 5003,
            apRefundDepositPayment: 5004,
            apRefundDepositMutation: 5005,
            apCommissionList: 5006,
            apCommissionAgingReport: 5007,
            apCommissionAgingReportDetail: 5008,
            apCommissionPayment: 5009,
            apCommissionMutation: 5010,
            logUser: 6501,
            logShift: 6509,
            logMoveRoom: 6502,
            logVoidTransaction: 6506,
            logHouseKeeping: 6507,
            logTransferTransaction: 6503,
            logSpecialAccess: 6504,
            keyLockHistory: 6505,
            logPABX: 6508,
        },

        reportID: {
            registrationFormReservation: 90001,
            registrationFormInHouse: 90002,
            receipt: 91000,
            receiptDeposit: 91001,
            receiptFolio: 91002,
            proformaInvoice: 92001,
            proformaInvoiceDetail: 92002,
            confirmationLetter: 92003,
            cashierReport: 2006,
            folio: 93001,
            roomCheckList: 94001,

            cityLedgerInvoice: 95001,
            invoicePaymentReceive: 95002,
        },
        // Access user MenuOrder
        accessUserMenuOrder: {
            // Front Desk
            dashboard: 0,
            floorPlan: 1,
            availability: 2,
            roomAvailability: 3,
            reservation: 4,
            guestGroup: 5,
            guestInHouse: 6,
            masterFolio: 7,
            deskFolio: 8,
            foliosAndTransaction: 9,
            folioHistory: 10,
            breakfastControl: 11,
            houseKeeping: 12,
            roomCosting: 13,
            guestLoanItem: 14,
            lostAndFound: 15,
            cashierReport: 16,
            // Night Audit
            competitorData: 17,
            globalPostTransaction: 18,
            autoPostTransaction: 19,
            dayendClose: 20,
            // Marketing
            company: 21,
            package: 22,
            roomRate: 23,
            eventList: 24,
            phoneBook: 25,
            member: 26,
            voucher: 27,
            // Back Office
            apRefundDeposit: 28,
            apCommissionAndOther: 29,
            arCityLedger: 30,
            arCityLedgerInvoice: 31,
            receipt: 32,
            bankTransaction: 33,
            bankReconciliation: 34,
            cheque: 35,
            exportJournal: 36,
            incomeBudget: 37,
            budgetStatistic: 38,
            report: 39,
            dataAnalysis: 40,
            // Tool
            configuration: 41,
            notification: 42,
            user: 43,
            userGroup: 44,
            oneTimePassword: 45,
            userActivityLog: 46,
            pABXSMDRViewer: 47,
            backUpDatabase: 48,
            restoreDatabase: 49,
            optimizeData: 50,
            wallpaper: 51,
        },

        accessSpecialOrder: {
            unlockReservation: 0,
            voidReservation: 1,
            voidDeposit: 2,
            correctDeposit: 3,
            decreaseStay: 4,
            scheduledRate: 5,
            breakdown: 6,
            extraCharge: 7,
            complimentGuest: 8,
            houseUseGuest: 9,
            moveRoom: 10,
            voidSubFolio: 11,
            correctSubFolio: 12,
            cancelCheckIn: 13,
            cancelCheckOut: 14,
            createMasterFolio: 15,
            printMoreInvoice: 16,
            modifyClosedJournal: 17,
            transfertoDeskFolio: 18,
            transfertoMasterFolio: 19,
            businessSource: 20,
            overrideRateDiscount: 21,
        },

        otherAccessOrder: {
            editReport: 0,
            exportReport: 1,
            customizeReport: 2,
            // deposit tool
            insertDeposit: 3,
            cashDeposit: 4,
            cardDeposit: 5,
            cashRefundDeposit: 6,
            voidDeposit: 7,
            correctionDeposit: 8,
            transferDeposit: 9,
            updateRemarkDeposit: 10,
            updateSubDepartmentDeposit: 11,
            updateDocumentNumberDeposit: 12,
            // folio transaction
            chargeTransaction: 13,
            cashTransaction: 14,
            cardTransaction: 15,
            directBillTransaction: 16,
            updateDirectBillTransaction: 17,
            cashRefundTransaction: 18,
            otherPaymentTransaction: 19,
            voidTransaction: 20,
            correctionTransaction: 21,
            transferTransaction: 22,
            updateSubDepartmentTransaction: 23,
            updateRemarkTransaction: 24,
            updateDocumentNumberTransaction: 25,
            checkOut: 26,
            printFolio: 27,
        },

        tableName: {
            accApAr: 0,
            accApArPaymentDetail: 1,
            accApArCommissionPaymentDetail: 2,
            accApCommissionPayment: 3,
            accApCommissionPaymentDetail: 4,
            accApNoShowPayment: 5,
            accApNoShowPaymentDetail: 6,
            accCashSaleRecon: 7,
            accCfgInitBankAccount: 8,
            accCloseMonth: 9,
            accCloseYear: 10,
            accConstBankAccountType: 11,
            accConstJournalGroup: 12,
            accConstJournalType: 13,
            accCreditCardRecon: 14,
            accCreditCardReconDetail: 15,
            accForeignCash: 16,
            accImportJournalLog: 17,
            accJournal: 18,
            accJournalDetail: 19,
            accPrepaidExpense: 20,
            accPrepaidExpensePosted: 21,
            accReport: 22,
            accReportDefaultField: 23,
            accReportGroupField: 24,
            accReportGroupingField: 25,
            accReportOrderField: 26,
            accReportTemplate: 27,
            accReportTemplateField: 28,
            accUserGroup: 29,
            astCfgInitShippingAddress: 30,
            astConstPurchaseRequestStatus: 31,
            astConstStoreRequisitionStatus: 32,
            astReport: 33,
            astReportDefaultField: 34,
            astReportGroupField: 35,
            astReportGroupingField: 36,
            astReportOrderField: 37,
            astReportTemplate: 38,
            astReportTemplateField: 39,
            astUserGroup: 40,
            astUserSubDepartment: 41,
            auditLog: 42,
            banBooking: 43,
            banCfgInitSeatingPlan: 44,
            banCfgInitTheme: 45,
            banCfgInitVenue: 46,
            banCfgInitVenueCombine: 47,
            banCfgInitVenueCombineDetail: 48,
            banCfgInitVenueGroup: 49,
            banConstBookingStatus: 50,
            banConstReservationStatus: 51,
            banConstReservationType: 52,
            banConstVenueLocation: 53,
            banReport: 54,
            banReportDefaultField: 55,
            banReportGroupField: 56,
            banReportGroupingField: 57,
            banReportOrderField: 58,
            banReportTemplate: 59,
            banReportTemplateField: 60,
            banReservation: 61,
            banReservationCharge: 62,
            banReservationRemark: 63,
            banUserGroup: 64,
            breakfastListTemp: 65,
            budgetExpense: 66,
            budgetFb: 67,
            budgetIncome: 68,
            budgetStatistic: 69,
            cashCount: 70,
            cfgInitAccount: 71,
            cfgInitAccountSubGroup: 72,
            cfgInitBedType: 73,
            cfgInitBookingSource: 74,
            cfgInitCardBank: 75,
            cfgInitCardType: 76,
            cfgInitCity: 77,
            cfgInitCompanyType: 78,
            cfgInitCompetitorCategory: 79,
            cfgInitContinent: 80,
            cfgInitCountry: 81,
            cfgInitCreditCardCharge: 82,
            cfgInitCurrency: 83,
            cfgInitCurrencyNominal: 84,
            cfgInitCustomLookupField01: 85,
            cfgInitCustomLookupField02: 86,
            cfgInitCustomLookupField03: 87,
            cfgInitCustomLookupField04: 88,
            cfgInitCustomLookupField05: 89,
            cfgInitCustomLookupField06: 90,
            cfgInitCustomLookupField07: 91,
            cfgInitCustomLookupField08: 92,
            cfgInitCustomLookupField09: 93,
            cfgInitCustomLookupField10: 94,
            cfgInitCustomLookupField11: 95,
            cfgInitCustomLookupField12: 96,
            cfgInitDepartment: 97,
            cfgInitGuestType: 98,
            cfgInitIdCardType: 99,
            cfgInitIs_FbSubDepartmentGroup: 100,
            cfgInitIs_Fb_SubDepartmentGroupDetail: 101,
            cfgInitJournalAccount: 102,
            cfgInitJournalAccountCategory: 103,
            cfgInitJournalAccountSubGroup: 104,
            cfgInitLanguage: 105,
            cfgInitLoanItem: 106,
            cfgInitMarket: 107,
            cfgInitMarketCategory: 108,
            cfgInitMarketing: 109,
            cfgInitMemberPointType: 110,
            cfgInitNationality: 111,
            cfgInitOwner: 112,
            cfgInitPackage: 113,
            cfgInitPackageBreakdown: 114,
            cfgInitPackageBusinessSource: 115,
            cfgInitPaymentType: 116,
            cfgInitPhoneBookType: 117,
            cfgInitPrinter: 118,
            cfgInitRegency: 119,
            cfgInitReservationMark: 120,
            cfgInitRoom: 121,
            cfgInitRoomAllotmentType: 122,
            cfgInitRoomAmenities: 123,
            cfgInitRoomBoy: 124,
            cfgInitRoomRate: 125,
            cfgInitRoomRateBreakdown: 126,
            cfgInitRoomRateBusinessSource: 127,
            cfgInitRoomRateCategory: 128,
            cfgInitRoomRateCurrency: 129,
            cfgInitRoomRateDynamic: 130,
            cfgInitRoomRateSubCategory: 131,
            cfgInitRoomType: 132,
            cfgInitRoomUnavailableReason: 133,
            cfgInitRoomView: 134,
            cfgInitState: 135,
            cfgInitSubDepartment: 136,
            cfgInitTaxAndService: 137,
            cfgInitTitle: 138,
            cfgInitVoucherReason: 139,
            cmUpdate: 140,
            company: 141,
            competitor: 142,
            competitorData: 143,
            configuration: 144,
            constAccountGroup: 145,
            constBudgetType: 146,
            constChargeFrequency: 147,
            constChargeType: 148,
            constCommissionType: 149,
            constCustomerDisplayVendor: 150,
            constDepartmentType: 151,
            constFolioStatus: 152,
            constFolioType: 153,
            constForecastDay: 154,
            constForecastMonth: 155,
            constForeignCashTableId: 156,
            constGuestStatus: 157,
            constImage: 158,
            constIptvVendor: 159,
            constJournalAccountGroup: 160,
            constJournalAccountSubGroupType: 161,
            constJournalAccountType: 162,
            constJournalPrefix: 163,
            constKeylockVendor: 164,
            constMemberType: 165,
            constMikrotikVendor: 166,
            constNotificationType: 167,
            constOtherIcon: 168,
            constOtpStatus: 169,
            constPaymentGroup: 170,
            constReportFont: 171,
            constReportFormat: 172,
            constReservationStatus: 173,
            constRoomBlockStatus: 174,
            constRoomStatus: 175,
            constSmsDestinationType: 176,
            constSmsRepeatType: 177,
            constStatisticAccount: 178,
            constSystem: 179,
            constTransactionType: 180,
            constVoucherStatus: 181,
            constVoucherStatusApprove: 182,
            constVoucherStatusSold: 183,
            constVoucherType: 184,
            contactPerson: 185,
            corCfgInitUnit: 186,
            corReport: 187,
            corReportDefaultField: 188,
            corReportGroupField: 189,
            corReportGroupingField: 190,
            corReportOrderField: 191,
            corReportTemplate: 192,
            corReportTemplateField: 193,
            corUserGroup: 194,
            creditCard: 195,
            dataAnalysis: 196,
            dataAnalysisQuery: 197,
            dataAnalysisQueryList: 198,
            events: 199,
            faCfgInitItem: 200,
            faCfgInitItemCategory: 201,
            faCfgInitLocation: 202,
            faCfgInitManufacture: 203,
            faConstDepreciationType: 204,
            faConstItemCondition: 205,
            faConstLocationType: 206,
            faDepreciation: 207,
            faList: 208,
            faLocationHistory: 209,
            faPurchaseOrder: 210,
            faPurchaseOrderDetail: 211,
            faReceive: 212,
            faReceiveDetail: 213,
            faRepair: 214,
            faRevaluation: 215,
            failedJobs: 216,
            fbStatistic: 217,
            folio: 218,
            folioList: 219,
            folioRouting: 220,
            forecastInHouseChangePax: 221,
            forecastMonthlyDay: 222,
            forecastMonthlyDayPrevious: 223,
            gridProperties: 224,
            guestBreakdown: 225,
            guestDeposit: 226,
            guestDepositTax: 227,
            guestDetail: 228,
            guestExtraCharge: 229,
            guestExtraChargeBreakdown: 230,
            guestGroup: 231,
            guestInHouse: 232,
            guestInHouseBreakdown: 233,
            guestLoanItem: 234,
            guestMessage: 235,
            guestProfile: 236,
            guestScheduledRate: 237,
            guestToDo: 238,
            hotelInformation: 239,
            invCfgInitItem: 240,
            invCfgInitItemCategory: 241,
            invCfgInit_ItemCategoryOtherCogs: 242,
            invCfgInit_ItemCategoryOtherCogs2: 243,
            invCfgInit_ItemCategoryOtherExpense: 244,
            invCfgInitItemGroup: 245,
            invCfgInitItemUom: 246,
            invCfgInitMarketList: 247,
            invCfgInitReturnStockReason: 248,
            invCfgInitStore: 249,
            invCfgInitUom: 250,
            invCloseLog: 251,
            invCostRecipe: 252,
            invCosting: 253,
            invCostingDetail: 254,
            invOpname: 255,
            invProduction: 256,
            invPurchaseOrder: 257,
            invPurchaseOrderDetail: 258,
            invPurchaseRequest: 259,
            invPurchaseRequestDetail: 260,
            invReceive: 261,
            invReceiveDetail: 262,
            invReturnStock: 263,
            invStockTransfer: 264,
            invStockTransferDetail: 265,
            invStoreRequisition: 266,
            invStoreRequisitionDetail: 267,
            invoice: 268,
            invoiceItem: 269,
            invoicePayment: 270,
            log: 271,
            logBackup: 272,
            logKeylock: 273,
            logMode: 274,
            logShift: 275,
            logSpecialAccess: 276,
            logUser: 277,
            logUserAction: 278,
            logUserActionGroup: 279,
            lostAndFound: 280,
            marketStatistic: 281,
            member: 282,
            memberGift: 283,
            memberPoint: 284,
            memberPointRedeem: 285,
            migrations: 286,
            notification: 287,
            oauthAccessTokens: 288,
            oauthAuthCodes: 289,
            oauthClients: 290,
            oauthPersonalAccessClients: 291,
            oauthRefreshTokens: 292,
            oneTimePassword: 293,
            pabxSmdr: 294,
            passwordResets: 295,
            phoneBook: 296,
            posCaptainOrder: 297,
            posCaptainOrderTransaction: 298,
            posCfgInitDiscountLimit: 299,
            posCfgInitMarket: 300,
            posCfgInitMemberOutletDiscount: 301,
            posCfgInit_MemberOutletDiscountDetail: 302,
            posCfgInitMemberProductDiscount: 303,
            posCfgInitOutlet: 304,
            posCfgInitPaymentGroup: 305,
            posCfgInitProduct: 306,
            posCfgInitProductCategory: 307,
            posCfgInitProductGroup: 308,
            posCfgInitRoomBoy: 309,
            posCfgInitTable: 310,
            posCfgInitTableType: 311,
            posCfgInitTenan: 312,
            posCfgInitWaitress: 313,
            posCheck: 314,
            posCheckTransaction: 315,
            posConstCheckType: 316,
            posConstComplimentType: 317,
            posConstDiscount: 318,
            posConstTimeSegment: 319,
            posInformation: 320,
            posIptvMenuOrder: 321,
            posMember: 322,
            posProductCosting: 323,
            posReport: 324,
            posReportDefaultField: 325,
            posReportGroupField: 326,
            posReportGroupingField: 327,
            posReportOrderField: 328,
            posReportTemplate: 329,
            posReportTemplateField: 330,
            posReservation: 331,
            posReservationTable: 332,
            posTableUnavailable: 333,
            posUserGroup: 334,
            posUserGroupOutlet: 335,
            proformaInvoiceDetail: 336,
            receipt: 337,
            report: 338,
            reportCustom: 339,
            reportCustomFavorite: 340,
            reportDefaultField: 341,
            reportGroupField: 342,
            reportGroupingField: 343,
            reportOrderField: 344,
            reportPivotTemp: 345,
            reportRoomRateStructureTemp: 346,
            reportRoomSales: 347,
            reportTemplate: 348,
            reportTemplateField: 349,
            reservation: 350,
            reservationExtraCharge: 351,
            reservationExtraChargeBreakdown: 352,
            reservationScheduledRate: 353,
            roomAllotment: 354,
            roomStatistic: 355,
            roomStatus: 356,
            roomUnavailable: 357,
            roomUnavailableHistory: 358,
            smsEvent: 359,
            smsOutbox: 360,
            smsSchedule: 361,
            subFolio: 362,
            subFolioGroup: 363,
            subFolioGrouping: 364,
            subFolioTax: 365,
            tempSubFolioBreakdown1: 366,
            tempSubFolioCorrectionBreakdown: 367,
            transactionList: 368,
            transactionListTax: 369,
            user: 370,
            userGroup: 371,
            users: 372,
            voucher: 373,
            workingShift: 374,
        },
    },
};
